package com.github.cimsbioko.server.controller.idgeneration;

public enum IdGeneratedFields {

    LOCATION_HIERARCHY_ID, LOCATION_NAME, LOCATION_ID,
    CHILD_LOC_NAME, CHILD_LOC_NAME_FIRST, CHILD_LOC_NAME_LAST,
    INDIVIDUAL_FNAME, INDIVIDUAL_MNAME, INDIVIDUAL_LNAME,
    SOCIALGROUP_NAME,
    FIELDWORKER_FNAME, FIELDWORKER_LNAME, LOCATION_PREFIX
}
