create table adultvpm (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), recordedDate date, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), visit_uuid varchar(32), primary key (uuid));
create table AsyncTask (uuid varchar(32) not null, md5Hash varchar(255), taskEndDate timestamp, taskName varchar(255), taskStartDate timestamp, totalCount bigint not null, primary key (uuid));
create table classExtension (uuid varchar(32) not null, answers varchar(255), description varchar(255), entityClass varchar(255), name varchar(255) not null, primType varchar(255), roundNumber integer, primary key (uuid));
create table death (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), ageAtDeath bigint, deathCause varchar(255), deathDate date not null, deathPlace varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), visitDeath_uuid varchar(32), primary key (uuid));
create table demrates (uuid varchar(32) not null, denominator varchar(255), endDate timestamp, event varchar(255), name varchar(255), startDate timestamp, primary key (uuid));
create table error (uuid varchar(32) not null, deleted boolean not null, errorMessage varchar(255), errorlog_uuid varchar(32), error_uuid varchar(32), primary key (uuid));
create table errorlog (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, dataPayload text, error_uuid varchar(32), fieldWorker_uuid varchar(32) not null, assignedTo varchar(255), entityType varchar(255), resolutionStatus varchar(255), dateOfResolution date, primary key (uuid));
create table extension (uuid varchar(32) not null, entityExtId varchar(255) not null, extensionValue varchar(255) not null, classExtension_uuid varchar(32), entity_uuid varchar(32), primary key (uuid));
create table fieldworker (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), extId varchar(255) not null, idPrefix integer, firstName varchar(255), lastName varchar(255), passwordHash char(60) not null, insertBy_uuid varchar(32), voidBy_uuid varchar(32), primary key (uuid));
create table FormInstance (uuid varchar(32) not null, formInstanceId varchar(255), primary key (uuid));
create table FormInstance_ValidationMessage (FormInstance_uuid varchar(32) not null, validationMessages_uuid varchar(32) not null, unique (validationMessages_uuid));
create table individual (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), dob date, dobAspect varchar(255), extId varchar(255) not null, firstName varchar(255), gender varchar(255), lastName varchar(255), middleName varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, father_uuid varchar(32), mother_uuid varchar(32), age integer, ageUnits varchar(32), phoneNumber varchar(32), otherPhoneNumber varchar(32), languagePreference varchar(255), pointOfContactName varchar(255), pointOfContactPhoneNumber varchar(32), dip integer, memberStatus varchar(32), nationality varchar(32), primary key (uuid));
create table inmigration (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), migType varchar(255), origin varchar(255), reason varchar(255), recordedDate date not null, unknownIndividual boolean, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32) not null, residency_uuid varchar(32) not null, visit_uuid varchar(32) not null, primary key (uuid));
create table location (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), extId varchar(255) not null, locationName varchar(255), locationType varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, locationHierarchy_uuid varchar(32), sectorName varchar(255), localityName varchar(255), communityName varchar(255), communityCode varchar(255), mapAreaName varchar(255), floorNumber integer, buildingNumber integer, provinceName varchar(255), districtName varchar(255), subDistrictName varchar(255), longitude varchar(255), latitude varchar(255), accuracy varchar(255), altitude varchar(255), description varchar(255), regionName varchar(255), primary key (uuid));
create table locationhierarchy (uuid varchar(32) not null, extId varchar(255) not null, name varchar(255) not null, level_uuid varchar(32), parent_uuid varchar(32), primary key (uuid));
create table locationhierarchylevel (uuid varchar(32) not null, keyIdentifier integer not null, name varchar(255) not null, primary key (uuid));
create table membership (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), bIsToA varchar(255), endDate date, endType varchar(255), startDate date, startType varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), socialGroup_uuid varchar(32), primary key (uuid));
create table neonatalvpm (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), recordedDate date, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), visit_uuid varchar(32), primary key (uuid));
create table note (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), description varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, observationDate date, primary key (uuid));
create table outcome (uuid varchar(32) not null, type varchar(255), child_uuid varchar(32), childMembership_uuid varchar(32), pregnancyOutcome_uuid varchar(32), primary key (uuid));
create table outmigration (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), destination varchar(255), reason varchar(255), recordedDate date not null, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32) not null, residency_uuid varchar(32) not null, visit_uuid varchar(32), primary key (uuid));
create table postneonatalvpm (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), recordedDate date, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), visit_uuid varchar(32), primary key (uuid));
create table pregnancyobservation (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), expectedDeliveryDate date not null, recordedDate date not null, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, mother_uuid varchar(32), visit_uuid varchar(32) not null, primary key (uuid));
create table pregnancyoutcome (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), childEverBorn integer, numberOfLiveBirths integer, outcomeDate date, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, father_uuid varchar(32), mother_uuid varchar(32), visit_uuid varchar(32), primary key (uuid));
create table privilege (uuid varchar(32) not null, privilege varchar(255), primary key (uuid));
create table relationship (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), aIsToB varchar(255), endDate date, endType varchar(255), startDate date not null, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individualA_uuid varchar(32), individualB_uuid varchar(32), primary key (uuid));
create table residency (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), endDate date, endType varchar(255), startDate date not null, startType varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, individual_uuid varchar(32), location_uuid varchar(32), primary key (uuid));
create table role (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), description varchar(255), name varchar(255), insertBy_uuid varchar(32), voidBy_uuid varchar(32), primary key (uuid));
create table role_privileges (role_uuid varchar(32) not null, privilege_uuid varchar(32) not null, primary key (role_uuid,privilege_uuid));
create table round (uuid varchar(32) not null, endDate date, remarks varchar(255), roundNumber integer, startDate date, primary key (uuid));
create table socialgroup (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), extId varchar(255), groupName varchar(255), groupType varchar(255), insertBy_uuid varchar(32), location_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, groupHead_uuid varchar(32), primary key (uuid));
create table users (uuid varchar(32) not null, deleted boolean not null, description varchar(255), firstName varchar(255), fullName varchar(255), lastLoginTime bigint not null, lastName varchar(255), password varchar(255), sessionId varchar(255), username varchar(255), primary key (uuid));
create table user_roles (user_uuid varchar(32) not null, role_uuid varchar(32) not null, primary key (user_uuid,role_uuid));
create table vaccination (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), bcg date, dpt1 date, dpt2 date, dpt3 date, measels date, polio1 date, polio2 date, polio3 date, polio4 date, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, child_uuid varchar(32), primary key (uuid));
create table ValidationMessage (uuid varchar(32) not null, message varchar(255), primary key (uuid));
create table visit (uuid varchar(32) not null, deleted boolean not null, insertDate timestamp, voidDate timestamp, voidReason varchar(255), status varchar(255), statusMessage varchar(255), extId varchar(255), roundNumber integer, visitDate date not null, insertBy_uuid varchar(32), voidBy_uuid varchar(32), collectedBy_uuid varchar(32) not null, visitLocation_uuid varchar(32), primary key (uuid));
create table whitelist (uuid varchar(32) not null, address varchar(255), primary key (uuid));

alter table adultvpm add constraint FK_20kblwnvmg71qhuvkehtrq7a9 foreign key (individual_uuid) references individual (uuid);
alter table adultvpm add constraint FK_evi0xldcbvh7nluu8j7din6vq foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table adultvpm add constraint FK_r655056re5gh8i2mv1jcn69h8 foreign key (voidBy_uuid) references users (uuid);
alter table adultvpm add constraint FK_rfuwbqmo0b7gecdybyg5wst4o foreign key (insertBy_uuid) references users (uuid);
alter table adultvpm add constraint FK_so60ned0ih3aoee4po0kc2jvi foreign key (visit_uuid) references visit (uuid);
alter table death add constraint FK5B0927436F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table death add constraint FK5B0927468E8A298 foreign key (visitDeath_uuid) references visit (uuid);
alter table death add constraint FK5B0927480470E9E foreign key (individual_uuid) references individual (uuid);
alter table death add constraint FK5B0927497735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table death add constraint FK5B09274A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table error add constraint FK_1jowmiyejvpy90wiftcb9ioam foreign key (error_uuid) references errorlog (uuid);
alter table error add constraint error_ibfk_1 foreign key (errorlog_uuid) references errorlog (uuid);
alter table errorlog add constraint FK_jlm6epx6iul1gq5jg9kuf1cy foreign key (fieldWorker_uuid) references fieldworker (uuid);
alter table errorlog add constraint errorlog_ibfk_1 foreign key (error_uuid) references error (uuid);
alter table extension add constraint FKDB7D1C3FE3D6A93E foreign key (classExtension_uuid) references classExtension (uuid);
alter table extension add constraint FKDB7D1C3FEA9B72FE foreign key (entity_uuid) references visit (uuid);
alter table fieldworker add constraint FK528ED0F897735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table fieldworker add constraint FK528ED0F8A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table FormInstance_ValidationMessage add constraint FK565F30085537B136 foreign key (validationMessages_uuid) references ValidationMessage (uuid);
alter table FormInstance_ValidationMessage add constraint FK565F3008A1616787 foreign key (FormInstance_uuid) references FormInstance (uuid);
alter table individual add constraint FKFD3DA29930076DBB foreign key (father_uuid) references individual (uuid);
alter table individual add constraint FKFD3DA29936F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table individual add constraint FKFD3DA29997735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table individual add constraint FKFD3DA2999E4C80B4 foreign key (mother_uuid) references individual (uuid);
alter table individual add constraint FKFD3DA299A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table inmigration add constraint FKD6922049301AAA96 foreign key (visit_uuid) references visit (uuid);
alter table inmigration add constraint FKD692204936F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table inmigration add constraint FKD692204980470E9E foreign key (individual_uuid) references individual (uuid);
alter table inmigration add constraint FKD6922049851505F6 foreign key (residency_uuid) references residency (uuid);
alter table inmigration add constraint FKD692204997735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table inmigration add constraint FKD6922049A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table location add constraint FK714F9FB536F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table location add constraint FK714F9FB597735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table location add constraint FK714F9FB5A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table location add constraint FK714F9FB5DFDC7027 foreign key (locationHierarchy_uuid) references locationhierarchy (uuid);
alter table locationhierarchy add constraint FK6AD2CE2064C0094C foreign key (parent_uuid) references locationhierarchy (uuid);
alter table locationhierarchy add constraint FK6AD2CE20F61555E foreign key (level_uuid) references locationhierarchylevel (uuid);
alter table membership add constraint FKB01D87D636F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table membership add constraint FKB01D87D680470E9E foreign key (individual_uuid) references individual (uuid);
alter table membership add constraint FKB01D87D691408DD6 foreign key (socialGroup_uuid) references socialgroup (uuid);
alter table membership add constraint FKB01D87D697735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table membership add constraint FKB01D87D6A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table neonatalvpm add constraint FK_8r7ooyq5581a2o39pgd48lvba foreign key (voidBy_uuid) references users (uuid);
alter table neonatalvpm add constraint FK_ca1ck938c05ego4kcg5a49p9q foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table neonatalvpm add constraint FK_cft9odausxjup7qgn1npdwysb foreign key (insertBy_uuid) references users (uuid);
alter table neonatalvpm add constraint FK_o4sivvjyc1w2bu5j8rv1v7n3l foreign key (individual_uuid) references individual (uuid);
alter table neonatalvpm add constraint FK_to0uytmwx9cd3nfb36gq07wmk foreign key (visit_uuid) references visit (uuid);
alter table note add constraint FK33AFF236F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table note add constraint FK33AFF297735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table note add constraint FK33AFF2A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table outcome add constraint FKB21C0752948AAZE foreign key (pregnancyOutcome_uuid) references pregnancyoutcome (uuid);
alter table outcome add constraint FKBE0C075286CD7C22 foreign key (childMembership_uuid) references membership (uuid);
alter table outcome add constraint FKBE0C0752948ED5FB foreign key (child_uuid) references individual (uuid);
alter table outmigration add constraint FKE109DC40301AAA96 foreign key (visit_uuid) references visit (uuid);
alter table outmigration add constraint FKE109DC4036F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table outmigration add constraint FKE109DC4080470E9E foreign key (individual_uuid) references individual (uuid);
alter table outmigration add constraint FKE109DC40851505F6 foreign key (residency_uuid) references residency (uuid);
alter table outmigration add constraint FKE109DC4097735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table outmigration add constraint FKE109DC40A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table postneonatalvpm add constraint FK_5r1jemkatcnd2gsi4p1t2ajqq foreign key (insertBy_uuid) references users (uuid);
alter table postneonatalvpm add constraint FK_cx75kd6k7xd0mn6yjdkwdd892 foreign key (visit_uuid) references visit (uuid);
alter table postneonatalvpm add constraint FK_he6xapg3gg7n4kners36f389a foreign key (individual_uuid) references individual (uuid);
alter table postneonatalvpm add constraint FK_oaw9s0bggae9qd8g7a4a84e1 foreign key (voidBy_uuid) references users (uuid);
alter table postneonatalvpm add constraint FK_rvfhkkojxo8f7g74wje2esb69 foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table pregnancyobservation add constraint FKDB9E9ADF36F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table pregnancyobservation add constraint FKDB9E9ADF97735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table pregnancyobservation add constraint FKDB9E9ADF9E4C80B4 foreign key (mother_uuid) references individual (uuid);
alter table pregnancyobservation add constraint FKDB9E9ADFA726FBE foreign key (voidBy_uuid) references users (uuid);
alter table pregnancyobservation add constraint FK_sxwl8yjwlg3qtr9nkrs3pj293 foreign key (visit_uuid) references visit (uuid);
alter table pregnancyoutcome add constraint FKA53B1B8530076DBB foreign key (father_uuid) references individual (uuid);
alter table pregnancyoutcome add constraint FKA53B1B85301AAA96 foreign key (visit_uuid) references visit (uuid);
alter table pregnancyoutcome add constraint FKA53B1B8536F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table pregnancyoutcome add constraint FKA53B1B8597735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table pregnancyoutcome add constraint FKA53B1B859E4C80B4 foreign key (mother_uuid) references individual (uuid);
alter table pregnancyoutcome add constraint FKA53B1B85A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table relationship add constraint FKF064763836F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table relationship add constraint FKF064763897735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table relationship add constraint FKF0647638995599AF foreign key (individualA_uuid) references individual (uuid);
alter table relationship add constraint FKF06476389B0A724E foreign key (individualB_uuid) references individual (uuid);
alter table relationship add constraint FKF0647638A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table residency add constraint FK7E9A5B1A36F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table residency add constraint FK7E9A5B1A80470E9E foreign key (individual_uuid) references individual (uuid);
alter table residency add constraint FK7E9A5B1A97735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table residency add constraint FK7E9A5B1AA726FBE foreign key (voidBy_uuid) references users (uuid);
alter table residency add constraint FK7E9A5B1AB374291E foreign key (location_uuid) references location (uuid);
alter table role add constraint FK35807697735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table role add constraint FK358076A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table role_privileges add constraint FK797EEF4B1920CBBE foreign key (role_uuid) references role (uuid);
alter table role_privileges add constraint FK797EEF4B21E9AC56 foreign key (privilege_uuid) references privilege (uuid);
alter table socialgroup add constraint FK89CF7B3236F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table socialgroup add constraint FK89CF7B329001C018 foreign key (groupHead_uuid) references individual (uuid);
alter table socialgroup add constraint FK89CF7B3297735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table socialgroup add constraint FK89CF7B32A726FBE foreign key (voidBy_uuid) references users (uuid);
alter table socialgroup add constraint locationReferenceIndex foreign key (location_uuid) references location (uuid);
alter table user_roles add constraint FK734299491920CBBE foreign key (role_uuid) references role (uuid);
alter table user_roles add constraint FK73429949195798DE foreign key (user_uuid) references users (uuid);
alter table vaccination add constraint FK_5ft5gaveru9d496xcodkrkn72 foreign key (child_uuid) references individual (uuid);
alter table vaccination add constraint FK_6cf0ujkwii5nudfrq7hpr8xjf foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table vaccination add constraint FK_7mx1g0kw39t8jwteg7vl7kdpi foreign key (insertBy_uuid) references users (uuid);
alter table vaccination add constraint FK_j5332wyj5jjm2erbvugfvw7l5 foreign key (voidBy_uuid) references users (uuid);
alter table visit add constraint FK6B04D4B36F4BE6E foreign key (collectedBy_uuid) references fieldworker (uuid);
alter table visit add constraint FK6B04D4B97735AF9 foreign key (insertBy_uuid) references users (uuid);
alter table visit add constraint FK6B04D4BA726FBE foreign key (voidBy_uuid) references users (uuid);
alter table visit add constraint FK6B04D4BEC630DB3 foreign key (visitLocation_uuid) references location (uuid);

create or replace view v_individual_max_residency as select distinct on (individual_uuid) individual_uuid, uuid from residency where not deleted order by individual_uuid, startDate desc;
create or replace view v_individual_sync as select i.uuid as uuid, to_char(i.dob,'YYYY-MM-DD') as dob, i.extId as extId, i.father_uuid as father, case i.firstName when 'null' then null else i.firstName end as firstName, i.gender as gender, case i.lastName when 'null' then null else i.lastName end as lastName, i.mother_uuid as mother, rl.uuid as currentResidence, r.endType as endType, case i.middleName when 'null' then null else i.middleName end as otherNames, i.age as age, i.ageUnits as ageUnits, case i.phoneNumber when 'null' then null else i.phoneNumber end as phoneNumber, case i.otherPhoneNumber when 'null' then null else i.otherPhoneNumber end as otherPhoneNumber, case i.pointOfContactName when 'null' then null else i.pointOfContactName end as pointOfContactName, case i.pointOfContactPhoneNumber when 'null' then null else i.pointOfContactPhoneNumber end as pointOfContactPhoneNumber, i.languagePreference as languagePreference, case i.memberStatus when 'null' then null else i.memberStatus end as memberStatus, case i.nationality when 'null' then null else i.nationality end as nationality, case i.dip when 0 then null else i.dip end as otherId from individual i left join v_individual_max_residency mr on i.uuid = mr.individual_uuid left join residency r on mr.uuid = r.uuid left join location rl on r.location_uuid = rl.uuid where not i.deleted and i.extId <> 'UNK' and r.uuid is not null;
create or replace view v_fieldworker_sync as select uuid, extId, idPrefix, firstName, lastName, passwordHash as password from fieldworker where not deleted and extId <> 'UNK';
create or replace view v_locationhierarchy_sync as select lh.uuid, lh.extId, lh.name, l.name as level, lh.parent_uuid as parent from locationhierarchy lh join locationhierarchylevel l on lh.level_uuid = l.uuid;
create or replace view v_location_sync as select l.uuid, l.extId, locationHierarchy_uuid as hierarchyUuid, lh.extId as hierarchyExtId, case locationName when 'null' then 'Unnamed' else locationName end as name, description, communityName, communityCode, localityName, mapAreaName, sectorName, buildingNumber, floorNumber, case latitude when 'null' then null else latitude end as latitude, case longitude when 'null' then null else longitude end as longitude from location l join locationhierarchy lh on l.locationHierarchy_uuid = lh.uuid where not l.deleted;
create or replace view v_membership_sync as select uuid, individual_uuid, bIsToA as relationshipToHead, socialGroup_uuid from membership where not deleted;
create or replace view v_relationship_sync as select uuid, individualA_uuid as individualA, individualB_uuid as individualB, aIsToB as relationshipType, to_char(startDate,'YYYY-MM-DD') as startDate from relationship where not deleted;
create or replace view v_socialgroup_sync as select uuid, groupHead_uuid, location_uuid, groupName from socialgroup where not deleted and location_uuid is not null;
create or replace view v_visit_sync as select uuid, extId, visitLocation_uuid as location_uuid, to_char(visitDate,'YYYY-MM-DD') as date, collectedBy_uuid as fieldworkerUuid, roundNumber as round from visit where not deleted;
